name: Continuous integration for rest spring boot

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
    - name: Build Application Jar
      working-directory: ./rest-with-spring-boot
      run: mvn clean package
      
    - name: Docker compose build
      working-directory: ./
      run: docker compose build
      
    - name: Pusing the docker push
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest
        
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
